import type { Metadata } from "next";
import { playfairFont, poppinsFont } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"),
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairFont.variable} ${poppinsFont.variable} ${poppinsFont.className} antialiased`}
        style={{ fontFamily: poppinsFont.style.fontFamily }}
      >
        {children}
      </body>
    </html>
  );
}
